spring.application.name=eventmanagement
server.port=8080
spring.datasource.url=jdbc:mysql://localhost:3306/event_tickets
spring.datasource.username=tai_khoan_nick_ban
spring.datasource.password=doi_mat_khau_cua_ban
spring.jpa.hibernate.ddl-auto=update